### ISSUE TITLE
Protein names for plotting

### ISSUE THREAD

**Issue by mpullins** [DevinLayneShirley/Bioinformatics_Group_Project#1]
I'm not sure which is protein 1, protein 2, etc. But I made my bar graphs with these labels.

Do we want to rename the proteins for clarity and so they can be visually compared on the graphs? So, protein 1 would be Lhx2, Protein 2 would be Gsta2, Slc7a12, Ptpn5, Atp12a, Synpr.. ?

**Comment by DevinLayneShirley** [comment]
Done
